Added the karma.conf.js and updated npm package.json file to load alll the required packages for running unit test
Installing Karma and plugins
The recommended approach is to install Karma (and all the plugins your project needs) locally in the project's directory.
# Install Karma:
$ npm install karma --save-dev
$ npm install -g karma-cli

# Install plugins that your project needs:
$ npm install karma-jasmine karma-chrome-launcher jasmine-core --save-dev

# generates the karma.conf.js file:
$ karma init
This generates the karma.conf.js file that has information about which
	•  framework we are using(Jasmine, mocha)
	• Browser  - chrome,firefox
	• Location of test files etc.

# run the karma:
$ karma start karma.conf.js
Add below tag in karma.conf.js to automate the karma rum via = > $ npm test command
"scripts": {
    "test": "karma start karma.conf.js"
  }

npm install karma-mocha mocha --save-dev
npm install karma-chai-string --save-dev
npm install karma-chai --save-dev
npm install karma-chai-sinon --save-dev => some time this does not download correctly. In that case you need to clone from its git repo => https://github.com/domenic/sinon-chai
npm install karma-sinon sinon --save-dev

Issue =>
	1. Karma sometimes says on command prompt => File is removed
		○ Resolution => use the folder watch rather than.  =>
		'wwwroot/js/**/*.js'
	2. Bard is not defined
		○ Include bard in the list of files in karma.conf.js
	3. TypeError: angular.element.cleanData is not a function
		○ I had the same problem and what fixed it to me was to load jquery in my tests:
		 files: [
      'bower_components/jquery/dist/jquery.js',
      'bower_components/angular/angular.js',
      'bower_components/angular-mocks/angular-mocks.js',
...
]